### ISSUE TITLE
Страница добавления курса

### ISSUE THREAD

**Issue by Fr0ntman** [kursomir/markup2.0#10]
![6](https://cloud.githubusercontent.com/assets/17601801/23524048/15d20086-ff9a-11e6-922e-326c220894a5.png)

Отрисовать картинки с экшенами. Например: добавление/удаление переводчиков, лекций и т.д.

**Comment by gomzz** [comment]
Ага, разобрался с картинками, у меня просто оин скрипт был заблокирован.
Вот накидал. Критика, предложения..

Курс:
![_](https://cloud.githubusercontent.com/assets/19410418/23562665/d87a704c-005c-11e7-81fc-a4413576bc54.png)
![_ _2](https://cloud.githubusercontent.com/assets/19410418/23562670/db52c7e2-005c-11e7-8b2c-12e58c5b016a.png)
![_ _3](https://cloud.githubusercontent.com/assets/19410418/23562672/dd0737da-005c-11e7-93df-cec0440e32f8.png)
![_ _4](https://cloud.githubusercontent.com/assets/19410418/23562675/decfb57e-005c-11e7-9fda-13ab664cec58.png)

**Comment by basavind** [comment]
Мне нравится :)

@mixty1, @Fr0ntman и @AgDust — нужно ваше мнение

**Comment by agdust** [comment]
Для каждого абзаца отдельное текстовое поле со своей полосой редактирования? Неудобно, ИМХО. Можно ведь одное нормальное поле сделать, и в него уже вставлять и текст и видео и картинки.

Если вопрос именно в экшенах, то к ним никаких претензий нет, все логично и правильно :)

**Comment by basavind** [comment]
Это ведь страница курса, на которой будет одна картинка в заголовке и еще одна в "теле". Хотя наверное это уже похоже на оправдание костыля и можно действительно в панели редактирования рядом с кнопкой на ссылку добавить кнопку для картинки и видосика и они сами будут разрезать текстовое поле на сегменты.

Можно и Markdown запилить, вот такой какой-нибудь https://vuejs.org/v2/examples/ доступ к добавлению курсов явно будет у тех, кто слышал про md.

Но мне нравится как это симпотно выглядит 😀

**Comment by agdust** [comment]
Не-не-не, мне кажется не стоит резать, а оставить одним полем в пользу простоты реализации. Если включить md то все еще проще становится)

**Comment by basavind** [comment]
Под "разрезать" я имел ввиду, что вставляемая картинка будет на всю ширину поля для редактирования и будет "визуально разрезать" область редактирования.

**Comment by agdust** [comment]
Но если она одна, то зачем резать? В md картинка занимает строчку

**Comment by basavind** [comment]
Разрезает:
![default](https://cloud.githubusercontent.com/assets/1267239/23608268/b0043390-0279-11e7-8e79-d2794bba9bd8.png)

---

Не разрезает:
![default](https://cloud.githubusercontent.com/assets/1267239/23608274/b72be2da-0279-11e7-852e-d940b56b15e9.png)

**Comment by agdust** [comment]
Если так то может быть, я за то чтобы все было единым блоком и не резалось на абзацы. На первой картинке абзац внизу продолжается, то есть по сути они отличаются только размером

**Comment by mixty1** [comment]
@AgDust а чем плоха идея с отдельными блоками? И не обязательно чтобы один абзац был в одном блоке, можно и несколько абзацев.

**Comment by agdust** [comment]
Реализовать с одним блоком проще, ИМХО

**Comment by mixty1** [comment]
А мне кажется блоками удобнее, например картинку отдельно добавить проще, чем ковыряться в коде самого редактора

**Comment by mixty1** [comment]
![3](https://cloud.githubusercontent.com/assets/19410418/23562675/decfb57e-005c-11e7-9fda-13ab664cec58.png)
А вот тут предлагаю сделать вместо выпадающего меню просто darg & drop. Удаление сделать, если наведешь на лекцию, справа появляется кнопка-крестик. Редактирование - если на саму лекцию нажмешь, откроется страница для редактирования лекции.

**Comment by gomzz** [comment]
Для верстки:
https://drive.google.com/open?id=0BxYyQZYX47drT0ZkQ243Z1VKT1U
