### ISSUE TITLE
Страница курсов

### ISSUE THREAD

**Issue by gomzz** [kursomir/markup2.0#7]
![default](https://cloud.githubusercontent.com/assets/20019289/23519198/84aa0dc4-ff8f-11e6-9d4d-84131896a539.png)

Исходники: https://drive.google.com/open?id=0BxYyQZYX47drR3pHcDZUVnRrM1U

**Comment by gomzz** [comment]
![Uploading курсы.png…]()
![Uploading курсы_2.png…]()

**Comment by AgDust** [comment]
![default](https://cloud.githubusercontent.com/assets/20019289/23519198/84aa0dc4-ff8f-11e6-9d4d-84131896a539.png)
